name = "mi_mando"
description = "Calibrado con XJEmulator"

[[axes]]
source = "ABS_X"
target = "ABS_X"
invert = false
deadzone = 8000
scale = 258.008
center = 128

[[axes]]
source = "ABS_Y"
target = "ABS_Y"
invert = false
deadzone = 8000
scale = 258.008
center = 128

[[axes]]
source = "ABS_BRAKE"
target = "ABS_Z"
invert = false
deadzone = 0
scale = 1.000
center = 0

[[axes]]
source = "ABS_Z"
target = "ABS_RX"
invert = false
deadzone = 8000
scale = 258.008
center = 128

[[axes]]
source = "ABS_RZ"
target = "ABS_RY"
invert = false
deadzone = 8000
scale = 258.008
center = 128

[[axes]]
source = "ABS_GAS"
target = "ABS_RZ"
invert = false
deadzone = 0
scale = 1.000
center = 0

[[axes]]
source = "ABS_HAT0X"
target = "ABS_HAT0X"
invert = false
deadzone = 0
scale = 1.000
center = 0

[[axes]]
source = "ABS_HAT0Y"
target = "ABS_HAT0Y"
invert = false
deadzone = 0
scale = 1.000
center = 0

[[buttons]]
source = "BTN_SOUTH"
target = "BTN_A"

[[buttons]]
source = "BTN_EAST"
target = "BTN_B"

[[buttons]]
source = "BTN_NORTH"
target = "BTN_X"

[[buttons]]
source = "BTN_WEST"
target = "BTN_Y"

[[buttons]]
source = "BTN_TL"
target = "BTN_TL"

[[buttons]]
source = "BTN_TR"
target = "BTN_TR"

[[buttons]]
source = "BTN_SELECT"
target = "BTN_SELECT"

[[buttons]]
source = "BTN_START"
target = "BTN_START"

[[buttons]]
source = "BTN_MODE"
target = "BTN_MODE"

[[buttons]]
source = "BTN_THUMBL"
target = "BTN_THUMBL"

[[buttons]]
source = "BTN_THUMBR"
target = "BTN_THUMBR"

